name: Build and Deploy Handbook

on:
  # Trigger the workflow when changes in the handbook/ folder are pushed to the
  # main branch
  push:
    branches:
      - main
    paths:
      - "handbook/**"

jobs:
  # This job installs dependencies, builds the book, and pushes the generated
  # html files to the `gh-pages` branch
  build-and-deploy-book:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Install dependencies
      - name: Set up Python v3.10
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          pip install -r handbook/requirements.txt

      # Build the book
      - name: Build the book
        run: |
          jupyter-book build handbook

      # Deploy the book's HTML to gh-pages branch
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: handbook/_build/html
